2019-09-06 19:02:12,254 ERROR: Exception on / [GET] [in C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\xampp\htdocs\microblog\app\routes.py", line 29, in index
    prev_url=prev_url)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\xampp\htdocs\microblog\app\templates\index.html", line 21, in template
    {% endif %}
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\jinja2\parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\jinja2\parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\jinja2\parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\jinja2\parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\jinja2\parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2019-09-06 19:03:33,732 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:45]
2019-09-06 19:03:51,583 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:45]
2019-09-06 19:10:08,601 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:45]
2019-09-06 19:10:53,845 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:45]
2019-09-06 19:11:07,579 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:45]
2019-09-06 20:16:08,852 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:46]
2019-09-06 21:05:20,168 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:46]
2019-09-06 21:05:23,160 ERROR: Exception on / [GET] [in C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\xampp\htdocs\microblog\app\routes.py", line 17, in index
    form = PostForm()
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\flask_wtf\form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\wtforms\form.py", line 272, in __init__
    super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\wtforms\form.py", line 52, in __init__
    field = meta.bind_field(self, unbound_field, options)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\wtforms\meta.py", line 27, in bind_field
    return unbound_field.bind(form=form, **options)
  File "C:\xampp\htdocs\microblog\venv\lib\site-packages\wtforms\fields\core.py", line 353, in bind
    return self.field_class(*self.args, **kw)
TypeError: __init__() got an unexpected keyword argument 'placeholder'
2019-09-06 21:07:34,252 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:46]
2019-09-06 21:08:32,992 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:46]
2019-09-06 21:08:49,162 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:46]
2019-09-06 21:10:02,338 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:46]
2019-09-06 21:10:51,508 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:46]
2019-09-06 21:15:15,353 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:46]
2019-09-06 21:32:50,278 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-06 21:41:16,385 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-06 21:41:56,955 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-06 21:45:39,706 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-06 21:46:21,292 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-06 21:47:33,748 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-06 21:49:16,632 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-06 21:50:50,384 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-06 22:08:30,784 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-06 22:09:08,575 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-06 22:13:46,513 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-06 22:24:27,057 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-06 22:27:26,627 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-06 22:27:44,961 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-07 11:44:49,354 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-07 11:45:49,135 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-07 11:53:46,137 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-07 11:57:02,246 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-07 11:58:11,337 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-07 12:02:23,466 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
2019-09-07 12:12:17,549 INFO: Microblog startup [in C:\xampp\htdocs\microblog\app\__init__.py:47]
